FROM oven/bun
WORKDIR /app



COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/frontend/package.json ./apps/frontend/package.json
COPY ./packages  ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install

RUN bun run --cwd apps/frontend build

EXPOSE 5173

CMD ["bun", "run", "--cwd", "apps/frontend", "preview", "--host", "0.0.0.0", "--port", "5173"]