FROM oven/bun
WORKDIR /app


ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL


COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./apps/frontend/package.json ./apps/frontend/package.json
COPY ./packages  ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install

EXPOSE 5173

CMD ["bun", "run", "--cwd", "apps/frontend", "dev", "--host"]